name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"

    - name: Prepare docs directory
      run: |
        # Create docs directory if it doesn't exist
        mkdir -p docs

        # Clean docs directory
        rm -rf docs/*

        # Copy files from target to docs if they exist
        if [ -d "target" ] && [ -n "$(ls -A target 2>/dev/null)" ]; then
          echo "Copying files from target to docs..."
          cp -r target/* docs/
        else
          echo "No files found in target/"
        fi

        # Ensure there's at least index.md
        if [ ! -f docs/index.md ] && [ -z "$(ls -A docs 2>/dev/null)" ]; then
          echo "# Traducciones de Suttas Pali" > docs/index.md
          echo "Bienvenido al proyecto de traducción." >> docs/index.md
          echo "No hay traducciones publicadas todavía." >> docs/index.md
        fi

    - name: Convert TXT to MD
      run: |
        # Convert all .txt files to .md
        if ls docs/*.txt 1> /dev/null 2>&1; then
          for file in docs/*.txt; do
            mv "$file" "${file%.txt}.md"
          done
        fi

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material

    - name: Build with MkDocs
      run: mkdocs build --site-dir site

    - name: Verify build
      run: |
        # Check if index.html was created
        if [ ! -f site/index.html ]; then
          echo "ERROR: index.html was not created!"
          ls -la site/
          exit 1
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        force_orphan: true